export enum ActionTypes {
  // app action
  SET_THEME = "SET_THEME",
  SET_BASE_URL = "SET_BASE_URL",

  // user action
  SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN",
  SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN",
  SET_USER_INFO = "SET_USER_INFO",
  SET_USER_APP = "SET_USER_APP",
  SET_SELECTED_APP = "SET_SELECTED_APP",
  SET_SELECTED_APP_MENU_ITEMS = "SET_SELECTED_APP_MENU_ITEMS",
  SIGN_OUT = "SIGN_OUT",
}
